WITH CTE1 AS (
    SELECT HACKER_ID, COUNT(CHALLENGE_ID) AS CNT1
    FROM CHALLENGES
    GROUP BY HACKER_ID
),
CTE2 AS (
    SELECT CNT1, COUNT(CNT1) AS CNT2 FROM CTE1
    GROUP BY CNT1
    HAVING CNT1 = (SELECT MAX(CNT1) FROM CTE1)
        OR COUNT(CNT1) = 1
)
SELECT C1.HACKER_ID,HC.NAME, C1.CNT1 FROM CTE1 C1
INNER JOIN CTE2 C2 ON C1.CNT1 = C2.CNT1
INNER JOIN HACKERS HC ON HC.HACKER_ID = C1.HACKER_ID
ORDER BY C1.CNT1 DESC, C1.HACKER_ID ASC 

    
