SELECT A.HACKER_ID, HC.NAME, SUM(M_SCORE) FROM (
    SELECT HACKER_ID, CHALLENGE_ID, MAX(SCORE) AS M_SCORE
    FROM SUBMISSIONS 
    GROUP BY HACKER_ID, CHALLENGE_ID
) A
INNER JOIN HACKERS HC ON HC.HACKER_ID = A.HACKER_ID
GROUP BY A.HACKER_ID, HC.NAME
HAVING SUM(M_SCORE) <> 0
ORDER BY SUM(M_SCORE) DESC, A.HACKER_ID ASC
