WITH CTE1 AS (
    SELECT WP.AGE, MIN(W.COINS_NEEDED) AS COINS_NEEDED, W.POWER
    FROM WANDS W
    INNER JOIN WANDS_PROPERTY WP ON WP.CODE = W.CODE
    GROUP BY WP.AGE,W.POWER
)
SELECT W.ID, WP.AGE, MIN(W.COINS_NEEDED) AS COINS_NEEDED, W.POWER
FROM WANDS W
INNER JOIN WANDS_PROPERTY WP ON WP.CODE = W.CODE AND WP.IS_EVIL = 0
INNER JOIN CTE1 C1 ON C1.AGE=WP.AGE AND C1.COINS_NEEDED = W.COINS_NEEDED AND C1.POWER = W.POWER
GROUP BY W.ID, WP.AGE,W.POWER
ORDER BY POWER DESC, AGE DESC