SELECT HC.HACKER_ID, HC.NAME FROM HACKERS HC
INNER JOIN SUBMISSIONS SB ON SB.HACKER_ID = HC.HACKER_ID
INNER JOIN CHALLENGES CH ON CH.CHALLENGE_ID = SB.CHALLENGE_ID
INNER JOIN DIFFICULTY DF ON DF.DIFFICULTY_LEVEL = CH.DIFFICULTY_LEVEL
    AND DF.SCORE = SB.SCORE
GROUP BY HC.HACKER_ID, HC.NAME
HAVING COUNT(CH.CHALLENGE_ID) > 1
ORDER BY COUNT(CH.CHALLENGE_ID) DESC, HC.HACKER_ID ASC