DECLARE @COUNT AS INT = (SELECT COUNT('') FROM STATION);
SELECT ID, LAT_N, ROW_NUMBER() OVER(ORDER BY LAT_N) AS ROW_NUM 
INTO #TEMP
FROM STATION
IF (@COUNT%2) = 0
    BEGIN
        SELECT LAT_N FROM #TEMP
        WHERE ROW_NUM IN (SELECT ((@COUNT/2)+((@COUNT/2)+1)/2) FROM #TEMP)
    END
ELSE
    BEGIN
        SELECT CAST(LAT_N AS DECIMAL(18,4)) FROM #TEMP
        WHERE ROW_NUM IN (SELECT ((@COUNT+1)/2) FROM #TEMP)
    END